name: PR Automation

on:
  pull_request: {}
  pull_request_target:
    types:
      - closed
    branches:
      - master

env:
  APP_NAME: provider-virtuozzo
  PUSH_PACKAGE: "True"
  PUSH_IMAGE: "False"

jobs:
  check-labels:
    if: github.event.pull_request.number != 0
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:v1.6.51
        with:
          one_of: major,minor,patch,documentation,dependency
          repo_token: ${{ secrets.GITHUB_TOKEN }}

  publish-branch-images:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Determine Go version from go.mod
        run: echo "GO_VERSION=$(grep "go 1." go.mod | cut -d " " -f 2)" >> $GITHUB_ENV

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Extract escaped branch name
        shell: bash
        run: echo "branch=$(echo ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}} | sed 's/\//_/g' )" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build branch and push image
        if: env.PUSH_IMAGE == 'true'
        run: make docker-push-branchtag -e IMG_TAG="${{ steps.extract_branch.outputs.branch }}"

      - name: Build branch and push package
        if: env.PUSH_PACKAGE == 'True'
        run: make package-push-branchtag -e IMG_TAG="${{ steps.extract_branch.outputs.branch }}"

  create-release:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - name: Check for patch label
        if: contains(github.event.pull_request.labels.*.name, 'patch') || contains(github.event.pull_request.labels.*.name, 'dependency') || contains(github.event.pull_request.labels.*.name, 'documentation')
        id: patch
        run: |
          echo "set=true" >> $GITHUB_OUTPUT
      - name: Check for minor label
        if: contains(github.event.pull_request.labels.*.name, 'minor')
        id: minor
        run: |
          echo "set=true" >> $GITHUB_OUTPUT
      - name: Check for major label
        if: contains(github.event.pull_request.labels.*.name, 'major')
        id: major
        run: |
          echo "set=true" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-tags: true

      - name: fetch tags
        run: |
          git fetch --tags
          echo "latest tag: $(git describe --tags "$(git rev-list --tags --max-count=1)")"
          echo "TAG_VERSION=$(git describe --tags "$(git rev-list --tags --max-count=1)")" >>  $GITHUB_ENV

      - name: Increase Tag
        id: tag
        run: |
          patch=${{ steps.patch.outputs.set }}
          minor=${{ steps.minor.outputs.set }}
          major=${{ steps.major.outputs.set }}

          major_ver=$(echo '${{ env.TAG_VERSION }}' | cut -d "." -f1)
          minor_ver=$(echo '${{ env.TAG_VERSION }}' | cut -d "." -f2)
          patch_ver=$(echo '${{ env.TAG_VERSION }}' | cut -d "." -f3)

          major_ver="${major_ver:1}"

          # Check for patch label
          [ ! -z "$patch" ] && [ -z "$minor" ] && [ -z "$major" ] && ((patch_ver++)) || true

          # check for minor label
          if [ ! -z "$minor" ] && [ -z "$major" ]; then
            ((minor_ver++))
            patch_ver=0
          fi

          # Check for major label
          if [ ! -z "$major" ]; then
            ((major_ver++))
            minor_ver=0
            patch_ver=0
          fi

          tag="v$major_ver.$minor_ver.$patch_ver"
          echo "new tag $tag"
          git tag $tag
          git push --tags
          echo tag=$tag >> $GITHUB_OUTPUT
